UIREC-136: Update circulation interface dependency to support v11
folio-org/ui-receiving pull request #267
Opened 2021-05-20 12:27 UTC by Dmitriy-Litvinenko

## Purpose
There is a breaking change in mod-circulation (https://github.com/folio-org/mod-circulation/pull/854), circulation interface version will be updated to 11.0.  Other modules should update their dependencies to support this change.

**Do not merge. We have several associated pull request and we need merge them at the same time.**

**API changes**
circulation/override-renewal-by-barcode - will be removed
circulation/renew-by-barcode - request and response will be changed
Current changes will be effect ui-users module

## Refs
https://issues.folio.org/browse/UIREC-136

2021-05-20 12:35 UTC, Dmitriy-Litvinenko commented
@zburke @mkuklis @NikitaSedyx  Could you please review? Do you have permission for merge in current repository?

2021-05-20 12:41 UTC, NikitaSedyx commented on package.json
> +      "circulation": "9.5 10.0 11.0",
plz remove 9.5

2021-05-20 12:41 UTC, NikitaSedyx commented
I have permissions

2021-05-20 12:45 UTC, Dmitriy-Litvinenko commented on package.json
> +      "circulation": "9.5 10.0 11.0",
Fixed

2021-05-20 13:30 UTC, zburke requested changes
Technically, removing support for 9.5 is a breaking change for this repo, so if you're going to do that you need to bump the major version. I support this here since it keeps the support surface small. And unlike changing the major version of a plugin, it's no big deal here since only platforms depend on apps and we have `>=` deps in the platforms' `snapshot` branches at present. 

Still, it's good to be correct about these things. Eventually, we hope to move to `^` deps in the platforms so we can be more deliberate about things like this and about managing compatibility for major versions of apps' peer-deps (e.g. on `react`, `@folio/stripes`) so it's a good habit to get into, even if there is no real impact at present.

2021-05-20 14:11 UTC, Dmitriy-Litvinenko commented
@zburke @NikitaSedyx Could you please re-review?

2021-05-20 14:30 UTC, zburke approved these changes

2021-05-21 06:16 UTC, NikitaSedyx approved these changes

2021-05-21 13:05 UTC, merged