UIREC-291: add dropdown action buttons
folio-org/ui-receiving pull request #468
Opened 2023-12-12 09:29 UTC by alisher-epam

## Purpose

[UIREC-291](https://issues.folio.org/browse/UIREC-291) - Combine piece action buttons into action menu
## Approach

https://github.com/folio-org/ui-receiving/assets/116072773/58487517-9cba-4ef4-9086-932744bf6c2c

#### TODOS and Open Questions

## Learning

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2023-12-12 12:18 UTC, OleksandrHladchenko1 approved these changes

2023-12-12 12:58 UTC, UladzislauKutarkin approved these changes

2023-12-12 15:26 UTC, usavkov-epam requested changes

2023-12-12 15:26 UTC, usavkov-epam commented on src/TitleDetails/AddPieceModal/ModalActionButtons/ModalActionButtons.js
> +        onClick={onSave}
Add please `marginBottom0` here

2023-12-12 15:26 UTC, usavkov-epam commented on src/TitleDetails/AddPieceModal/ModalActionButtons/ModalActionButtons.js
> +        onClick={onSave}
`marginBottom0` plz

2023-12-12 15:26 UTC, usavkov-epam commented on src/TitleDetails/AddPieceModal/ModalActionButtons/ModalActionButtons.js
> +      <Dropdown buttonProps={{ buttonStyle: 'primary', buttonClass: css.dropdownButton }}>
```
{
  buttonStyle: 'primary',
  buttonClass: css.dropdownButton,
  marginBottom0: true,
}
```

2023-12-12 15:26 UTC, usavkov-epam commented on src/TitleDetails/AddPieceModal/ModalActionButtons/utils.js
> +export const getPieceActionMenus = ({ status, disabled, ...rest }) => {
is there any reason to destructure `disabled`?

2023-12-12 15:26 UTC, usavkov-epam commented on src/TitleDetails/AddPieceModal/ModalActionButtons/constants.js
> +    <Button disabled={disabled} buttonStyle="dropdownItem">
"Save and create another" stoped working here?

2023-12-12 15:27 UTC, usavkov-epam commented
It seems that "Save and create another" not working after changes

2023-12-12 15:28 UTC, usavkov-epam commented
https://github.com/folio-org/ui-receiving/assets/88109087/6caa5884-acbf-4bb4-87e6-6f1db979ebe6

2023-12-12 15:30 UTC, usavkov-epam commented
And I don't think we need "Delete" action for a new piece form

2023-12-13 12:17 UTC, usavkov-epam commented
Since we have the new action for "Save & create another", "Save&close" button should always save a piece and close the modal. Currently after clicking "Save & create another", `isCreateAnother` state stays the same for the next piece modal: "save&close" btn change label (it must not) and after clicking just "save" it open modal again (we have separate action for that).

https://github.com/folio-org/ui-receiving/assets/88109087/c88cc587-987a-4e1a-a38b-7f67c528ba44

2023-12-13 14:17 UTC, alisher-epam commented
@usavkov-epam here is the screen record for fixing

https://github.com/folio-org/ui-receiving/assets/116072773/7b33ed98-ea8c-40b1-9896-3641b312941c

2023-12-13 15:40 UTC, usavkov-epam commented on src/TitleDetails/AddPieceModal/AddPieceModal.js
> +    handleSubmit();
I've checked locally - it's not

2023-12-14 06:43 UTC, usavkov-epam commented on src/TitleDetails/AddPieceModal/ModalActionButtons/ModalActionButtons.css
> +  &::before, &:focus::before {
UX of the dropdown btn should be the same as for other btns

2023-12-14 06:53 UTC, usavkov-epam commented on src/TitleDetails/AddPieceModal/ModalActionButtons/ModalActionButtons.js
> +          {actionMenus}
why is it plural?

2023-12-14 07:00 UTC, usavkov-epam commented
Please check both `rtl` and `ltr` directions:

![image](https://github.com/folio-org/ui-receiving/assets/88109087/5250cc6a-ea35-423c-9fdf-ce78a8eed5bb)

2023-12-14 09:39 UTC, usavkov-epam approved these changes

2023-12-14 09:41 UTC, merged