UIREC-305 View piece status change log
folio-org/ui-receiving pull request #473
Opened 2023-12-26 11:25 UTC by usavkov-epam

## Purpose

https://issues.folio.org/browse/UIREC-305

## Approach

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2023-12-26 16:54 UTC, mariia-aloshyna requested changes

2023-12-26 16:54 UTC, mariia-aloshyna commented on src/TitleDetails/AddPieceModal/ReceivingStatusChangeLog/ReceivingStatusChangeLog.test.js
> +    expect(screen.getByText('ui-receiving.piece.statusChangeLog.column.status'));
```suggestion
    expect(screen.getByText('ui-receiving.piece.statusChangeLog.column.status')).toBeInTheDocument();
```

2023-12-27 08:32 UTC, usavkov-epam commented on src/TitleDetails/AddPieceModal/ReceivingStatusChangeLog/ReceivingStatusChangeLog.test.js
> +    expect(screen.getByText('ui-receiving.piece.statusChangeLog.column.status'));
Good catch, @mariia-aloshyna, thanks! Updated

2023-12-27 13:51 UTC, mariia-aloshyna approved these changes

2024-01-01 07:10 UTC, Terala-Priyanka approved these changes

2024-01-03 09:44 UTC, merged